import 'package:json_annotation/json_annotation.dart';

@JsonEnum()
enum Species {
  @JsonValue("Anteater")
  anteater,
  @JsonValue("Bear")
  bear,
  @JsonValue("Bird")
  bird,
  @JsonValue("Bull")
  bull,
  @JsonValue("Cat")
  cat,
  @JsonValue("Cub")
  cub,
  @JsonValue("Chicken")
  chicken,
  @JsonValue("Cow")
  cow,
  @JsonValue("Alligator")
  alligator,
  @JsonValue("Deer")
  deer,
  @JsonValue("Dog")
  dog,
  @JsonValue("Duck")
  duck,
  @JsonValue("Elephant")
  elephant,
  @JsonValue("Frog")
  frog,
  @JsonValue("Goat")
  goat,
  @JsonValue("Gorilla")
  gorilla,
  @JsonValue("Hamster")
  hamster,
  @JsonValue("Hippo")
  hippo,
  @JsonValue("Horse")
  horse,
  @JsonValue("Koala")
  koala,
  @JsonValue("Kangaroo")
  kangaroo,
  @JsonValue("Lion")
  lion,
  @JsonValue("Monkey")
  monkey,
  @JsonValue("Mouse")
  mouse,
  @JsonValue("Octopus")
  octopus,
  @JsonValue("Ostrich")
  ostrich,
  @JsonValue("Eagle")
  eagle,
  @JsonValue("Penguin")
  penguin,
  @JsonValue("Pig")
  pig,
  @JsonValue("Rabbit")
  rabbit,
  @JsonValue("Rhino")
  rhino,
  @JsonValue("Sheep")
  sheep,
  @JsonValue("Squirrel")
  squirrel,
  @JsonValue("Tiger")
  tiger,
  @JsonValue("Wolf")
  wolf,
}
